"""
Global configuration, constants, weights, and rubric definitions for ProspectusIQ.
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Base paths
BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
DB_PATH = DATA_DIR / "ipo_cache.db"
SAMPLE_FILINGS_DIR = DATA_DIR / "sample_filings"

# Ensure data directories exist
DATA_DIR.mkdir(exist_ok=True)
SAMPLE_FILINGS_DIR.mkdir(exist_ok=True)

# LLM Provider Configuration
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-flash-lite-latest")
GROK_API_KEY = os.getenv("GROK_API_KEY", "")
GROK_BASE_URL = os.getenv("GROK_BASE_URL", "https://api.x.ai/v1")
GROK_MODEL = os.getenv("GROK_MODEL", "grok-beta")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "")
OPENROUTER_BASE_URL = os.getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")
OPENROUTER_MODEL = os.getenv("OPENROUTER_MODEL", "meta-llama/llama-3.1-70b-instruct")

# Categorical Enum Definitions
VERDICTS = [
    "LONG_TERM_COMPOUNDER",
    "APPLY_FOR_LISTING_GAINS",
    "HIGH_RISK_SPECULATIVE",
    "AVOID"
]

EXPECTED_RETURNS = [
    "NEGATIVE",
    "0-10%",
    "10-25%",
    ">25%"
]

STATUS_TYPES = ["GREEN", "YELLOW", "RED"]
SEVERITY_TYPES = ["LOW", "MEDIUM", "CRITICAL"]
DIVERGENCE_VERDICTS = ["ALIGNED", "DANGEROUS_EUPHORIA", "UNWARRANTED_PESSIMISM"]

# Category Weights
CATEGORY_WEIGHTS = {
    "Capital Integrity": 0.50,
    "Earnings Quality & Moat": 0.30,
    "Market, Valuation & Sentiment": 0.20
}

# The 12-Factor Forensic Rubric
FORENSIC_FACTORS = [
    # Category 1: Capital Integrity (50%)
    {
        "id": 1,
        "name": "Use of Proceeds",
        "category": "Capital Integrity",
        "weight": 0.15,
        "criteria": "Ratio of Fresh Issue (reinvested in business growth) vs. Offer for Sale (promoters/PE exiting).",
        "red_flag": "OFS exceeds 60% of total issue size, or fresh capital is explicitly allocated to repay unsecured loans taken from promoters or sister entities."
    },
    {
        "id": 2,
        "name": "Pre-IPO Allotment Disparity",
        "category": "Capital Integrity",
        "weight": 0.10,
        "criteria": "Share price paid by promoters, founders, or pre-IPO venture funds in transactions during the preceding 18 months versus the upper IPO price band.",
        "red_flag": "Insiders received shares at a 70%+ discount within the last 12 months with no substantive transformation in business fundamentals."
    },
    {
        "id": 3,
        "name": "Related-Party Transactions & Siphoning",
        "category": "Capital Integrity",
        "weight": 0.10,
        "criteria": "Volume of sales, purchases, consulting fees, leases, or intellectual property royalties conducted with entities owned by promoters' relatives.",
        "red_flag": "Recurring royalties or uncollateralized loans funneling out to promoter-held private partnerships."
    },
    {
        "id": 4,
        "name": "Outstanding Litigations & Contingent Liabilities",
        "category": "Capital Integrity",
        "weight": 0.10,
        "criteria": "Total value of disputed tax demands, criminal allegations, or civil litigations against promoters and key subsidiaries measured against tangible net worth.",
        "red_flag": "Quantifiable litigation exposure exceeds 20% of net worth, or active criminal proceedings question managerial integrity."
    },
    {
        "id": 5,
        "name": "Promoter Holding & Pledge Status",
        "category": "Capital Integrity",
        "weight": 0.05,
        "criteria": "Post-issue promoter shareholding percentage and percentage of existing promoter shares encumbered or pledged to lenders.",
        "red_flag": "Post-IPO promoter holding drops below 30%, or any portion of promoter shares is pledged to financial institutions."
    },
    # Category 2: Earnings Quality & Moat (30%)
    {
        "id": 6,
        "name": "CFO vs. PAT Divergence",
        "category": "Earnings Quality & Moat",
        "weight": 0.10,
        "criteria": "Comparison of Cash Flow from Operations (CFO) versus Profit After Tax (PAT) over the past 3 fiscal years.",
        "red_flag": "PAT shows consistent growth while CFO is negative or declining, signaling aggressive revenue booking and uncollected trade receivables."
    },
    {
        "id": 7,
        "name": "Customer & Supplier Concentration",
        "category": "Earnings Quality & Moat",
        "weight": 0.10,
        "criteria": "Percentage of total revenue generated by Top 1, Top 3, and Top 5 clients; dependence on single-geography suppliers.",
        "red_flag": "Top 3 customers account for over 45% of total revenue with short-term, cancellable contracts."
    },
    {
        "id": 8,
        "name": "Operating Margin Stability & Pricing Power",
        "category": "Earnings Quality & Moat",
        "weight": 0.10,
        "criteria": "Operating EBITDA margin trajectory over 3 years in the face of raw material inflation.",
        "red_flag": "Margin compression exceeding 300 basis points year-over-year, indicating inability to pass on costs."
    },
    # Category 3: Market, Valuation & Sentiment (20%)
    {
        "id": 9,
        "name": "Valuation Multiple vs. Listed Peers",
        "category": "Market, Valuation & Sentiment",
        "weight": 0.10,
        "criteria": "IPO P/E, Price-to-Book (P/B), and EV/EBITDA compared against profitable, established listed peers.",
        "red_flag": "Asking valuation demands a 40%+ premium over market leaders without demonstrating superior return on equity (ROE)."
    },
    {
        "id": 10,
        "name": "Regulatory & Government Policy Vulnerability",
        "category": "Market, Valuation & Sentiment",
        "weight": 0.05,
        "criteria": "Reliance on government subsidies, special tax holidays, regulatory licenses, or exposure to looming regulatory tariff caps.",
        "red_flag": "Core revenue stream subject to active regulatory crackdowns or licensing risks."
    },
    {
        "id": 11,
        "name": "Anchor Lock-In Expiry Supply Cliff",
        "category": "Market, Valuation & Sentiment",
        "weight": 0.025,
        "criteria": "Total volume of shares allocated to anchor investors subject to 30-day (50%) and 90-day (remaining 50%) mandatory lock-in expiries.",
        "red_flag": "Massive anchor allotment volume relative to average daily trading volume, signaling steep price correction potential on Day 31."
    },
    {
        "id": 12,
        "name": "Forum Sentiment vs. Prospectus Reality",
        "category": "Market, Valuation & Sentiment",
        "weight": 0.025,
        "criteria": "Divergence between retail speculative hype (e.g., high grey-market premiums) and skeptical warnings uncovered in investor forums.",
        "red_flag": "High social media enthusiasm coupled with specific, factual warnings on investor boards regarding corporate governance or past bankruptcy history."
    }
]

# Benchmark IPO Registry (Used as infallible fallback & instant offline demo)
BENCHMARK_IPOS = [
    {
        "symbol": "SWIGGY",
        "company_name": "Swiggy Limited",
        "open_date": "2024-11-06",
        "close_date": "2024-11-08",
        "issue_size": "₹11,327 Cr",
        "price_band": "₹371 - ₹390",
        "issue_type": "Book Built",
        "sector": "Consumer Tech / Quick Commerce",
        "peers": ["ZOMATO.NS"],
        "summary": "India's leading consumer convenience platform offering food delivery and quick commerce (Instamart)."
    },
    {
        "symbol": "NSE",
        "company_name": "National Stock Exchange of India Limited",
        "open_date": "Upcoming",
        "close_date": "TBD",
        "issue_size": "₹10,000 Cr",
        "price_band": "₹3,150 - ₹3,300",
        "issue_type": "Book Built",
        "sector": "Financial Infrastructure / Exchange",
        "peers": ["BSE.NS", "MCX.NS"],
        "summary": "India's premier market infrastructure institution and the world's largest derivatives exchange by volume."
    },
    {
        "symbol": "AFCONS",
        "company_name": "Afcons Infrastructure Limited",
        "open_date": "2024-10-25",
        "close_date": "2024-10-29",
        "issue_size": "₹5,430 Cr",
        "price_band": "₹440 - ₹463",
        "issue_type": "Book Built",
        "sector": "Infrastructure EPC",
        "peers": ["LT.NS", "KEC.NS", "NCC.NS"],
        "summary": "Flagship infrastructure engineering and construction arm of the Shapoorji Pallonji Group."
    }
]
